local theme = require("custom.highlights.kitty_conf")

local others = {
--   Normal={fg=theme.base05,bg=theme.base00},
   Bold={fg=nil,bg=nil,bold=true},
   Debug={fg=theme.base08,bg=nil},
   Directory={fg=theme.base0D,bg=nil},
   Error={fg=theme.base00,bg=theme.base08},
   ErrorMsg={fg=theme.base08,bg=theme.base00},
   Exception={fg=theme.base08,bg=nil},
   FoldColumn={fg=theme.base0C,bg=theme.base01},
   Folded={fg=theme.base03,bg=theme.base01},
   IncSearch={fg=theme.base01,bg=theme.base09},
   Italic={fg=nil,bg=nil},
   Macro={fg=theme.base08,bg=nil},
   MatchParen={fg=nil,bg=theme.base03},
   ModeMsg={fg=theme.base0B,bg=nil},
   MoreMsg={fg=theme.base0B,bg=nil},
   Question={fg=theme.base0D,bg=nil},
   Search={fg=theme.base01,bg=theme.base0A},
   Substitute={fg=theme.base01,bg=theme.base0A},
   SpecialKey={fg=theme.base03,bg=nil},
   TooLong={fg=theme.base08,bg=nil},
   Underlined={fg=theme.base08,bg=nil},
   Visual={fg=nil,bg=theme.base02},
   VisualNOS={fg=theme.base08,bg=nil},
   WarningMsg={fg=theme.base08,bg=nil},
   WildMenu={fg=theme.base08,bg=theme.base0A},
   Title={fg=theme.base0D,bg=nil},
   Conceal={fg=theme.base0D,bg=theme.base00},
   Cursor={fg=theme.base00,bg=theme.base05},
   NonText={fg=theme.base03,bg=nil},
   LineNr={fg=theme.base03,bg=nil},
   SignColumn={fg=theme.base03,bg=nil},
   StatusLine={fg=theme.base04,bg=nil},
   StatusLineNC={fg=theme.base03,bg=nil},
   VertSplit={fg=theme.base02,bg=nil},
   ColorColumn={fg=nil,bg=theme.base01},
   CursorColumn={fg=nil,bg=theme.base01},
   CursorLine={fg=nil,bg=theme.base01},
   CursorLineNr={fg=theme.base04,bg=nil},
   QuickFixLine={fg=nil,bg=theme.base01},
   PMenu={fg=theme.base05,bg=theme.base01},
   PMenuSel={fg=theme.base01,bg=theme.base05},
   TabLine={fg=theme.base03,bg=theme.base01},
   TabLineFill={fg=theme.base03,bg=theme.base01},
   TabLineSel={fg=theme.base0B,bg=theme.base01},

   Boolean={fg=theme.base09,bg=nil},
   Character={fg=theme.base08,bg=nil},
   Comment={fg=theme.base03,bg=nil},
   Conditional={fg=theme.base0E,bg=nil},
   Constant={fg=theme.base09,bg=nil},
   Define={fg=theme.base0E,bg=nil},
   Delimiter={fg=theme.base0F,bg=nil},
   Float={fg=theme.base09,bg=nil},
   Function={fg=theme.base0D,bg=nil},
   Identifier={fg=theme.base08,bg=nil},
   Include={fg=theme.base0D,bg=nil},
   Keyword={fg=theme.base0E,bg=nil},
   Label={fg=theme.base0A,bg=nil},
   Number={fg=theme.base09,bg=nil},
   Operator={fg=theme.base05,bg=nil},
   PreProc={fg=theme.base0A,bg=nil},
   Repeat={fg=theme.base0A,bg=nil},
   Special={fg=theme.base0C,bg=nil},
   SpecialChar={fg=theme.base0F,bg=nil},
   Statement={fg=theme.base08,bg=nil},
   StorageClass={fg=theme.base0A,bg=nil},
   String={fg=theme.base0B,bg=nil},
   Structure={fg=theme.base0E,bg=nil},
   Tag={fg=theme.base0A,bg=nil},
   Todo={fg=theme.base0A,bg=theme.base01},
   Type={fg=theme.base0A,bg=nil},
   Typedef={fg=theme.base0A,bg=nil},

   DiffAdd={fg=theme.base0B,bg=theme.base01},
   DiffChange={fg=theme.base03,bg=theme.base01},
   DiffDelete={fg=theme.base08,bg=theme.base01},
   DiffText={fg=theme.base0D,bg=theme.base01},
   DiffAdded={fg=theme.base0B,bg=theme.base00},
   DiffFile={fg=theme.base08,bg=theme.base00},
   DiffNewFile={fg=theme.base0B,bg=theme.base00},
   DiffLine={fg=theme.base0D,bg=theme.base00},
   DiffRemoved={fg=theme.base08,bg=theme.base00},

   gitcommitOverflow={fg=theme.base08,bg=nil},
   gitcommitSummary={fg=theme.base0B,bg=nil},
   gitcommitComment={fg=theme.base03,bg=nil},
   gitcommitUntracked={fg=theme.base03,bg=nil},
   gitcommitDiscarded={fg=theme.base03,bg=nil},
   gitcommitSelected={fg=theme.base03,bg=nil},
   gitcommitHeader={fg=theme.base0E,bg=nil},
   gitcommitSelectedType={fg=theme.base0D,bg=nil},
   gitcommitUnmergedType={fg=theme.base0D,bg=nil},
   gitcommitDiscardedType={fg=theme.base0D,bg=nil},
   gitcommitBranch={fg=theme.base09,bg=nil,bold=true},
   gitcommitUntrackedFile={fg=theme.base0A,bg=nil},
   gitcommitUnmergedFile={fg=theme.base08,bg=nil,bold=true},
   gitcommitDiscardedFile={fg=theme.base08,bg=nil,bold=true},
   gitcommitSelectedFile={fg=theme.base0B,bg=nil,bold=true},

   mailQuoted1={fg=theme.base0A,bg=nil},
   mailQuoted2={fg=theme.base0B,bg=nil},
   mailQuoted3={fg=theme.base0E,bg=nil},
   mailQuoted4={fg=theme.base0C,bg=nil},
   mailQuoted5={fg=theme.base0D,bg=nil},
   mailQuoted6={fg=theme.base0A,bg=nil},
   mailURL={fg=theme.base0D,bg=nil},
   mailEmail={fg=theme.base0D,bg=nil},

   SpellBad={fg=nil,bg=nil,undercurl=true,special=theme.base08},
   SpellLocal={fg=nil,bg=nil,undercurl=true,special=theme.base0C},
   SpellCap={fg=nil,bg=nil,undercurl=true,special=theme.base0D},
   SpellRare={fg=nil,bg=nil,undercurl=true,special=theme.base0E},
}

return others
