local theme = require("custom.highlights.kitty_conf")


local ts_highlights = {
   TSannotation = { default = true, fg=theme.base0F, bg=nil, sp=nil},
   TSAttribute = { fg=theme.base0A, bg=nil, sp=nil, special=nil},
   TSCharacter = { fg=theme.base08, bg=nil, sp=nil, special=nil},
   TSConstBuiltin = { fg=theme.base09, bg=nil, sp=nil, special=nil},
   TSConstMacro = { fg=theme.base08, bg=nil, sp=nil, special=nil},
   TSError = { fg=theme.base08, bg=nil, sp=nil, special=nil},
   TSException = { fg=theme.base08, bg=nil, sp=nil, special=nil},
   TSFloat = { fg=theme.base09, bg=nil, sp=nil, special=nil},
   TSFuncBuiltin = { fg=theme.base0D, bg=nil, sp=nil, special=nil},
   TSFuncMacro = { fg=theme.base08, bg=nil, sp=nil, special=nil},
   TSKeywordFunction = { fg=theme.base0E, bg=nil, sp=nil, special=nil},
   TSKeywordOperator = { fg=theme.base0E, bg=nil, sp=nil, special=nil},
   TSMethod = { fg=theme.base0D, bg=nil, sp=nil, special=nil},
   TSNamespace = { fg=theme.base08, bg=nil, sp=nil, special=nil},
   TSNone = { fg=theme.base05, bg=nil, sp=nil, special=nil},
   TSParameter = { fg=theme.base08, bg=nil, sp=nil, special=nil},
   TSParameterReference = { fg=theme.base05, bg=nil, sp=nil, special=nil},
   TSPunctDelimiter = { fg=theme.base0F, bg=nil, sp=nil, special=nil},
   TSPunctSpecial = { fg=theme.base05, bg=nil, sp=nil, special=nil},
   TSStringRegex = { fg=theme.base0C, bg=nil, sp=nil, special=nil},
   TSStringEscape = { fg=theme.base0C, bg=nil, sp=nil, special=nil},
   TSSymbol = { fg=theme.base0B, bg=nil, sp=nil, special=nil},
   TSTagDelimiter = { fg=theme.base0F, bg=nil, sp=nil, special=nil},
   TSText = { fg=theme.base05, bg=nil, sp=nil, special=nil},
   TSStrong = { fg=nil, bg=nil, bold=true, special=nil},
   TSEmphasis = { fg=theme.base09, bg=nil, sp=nil, special=nil},
   TSStrike = { fg=theme.base00, bg=nil, strikethrough=true, special=nil},
   TSLiteral = { fg=theme.base09, bg=nil, sp=nil, special=nil},
   TSURI = { fg=theme.base09, bg=nil, underline=true, special=nil},
   TSTypeBuiltin = { fg=theme.base0A, bg=nil, sp=nil, special=nil},
   TSVariableBuiltin = { fg=theme.base09, bg=nil, sp=nil, special=nil},
   TSDefinition = { fg=nil, bg=nil, underline=true, special=theme.base04},
   TSDefinitionUsage = { fg=nil, bg=nil, underline=true, special=theme.base04},
   TSCurrentScope = { fg=nil, bg=nil, bold=true, special=nil},
}
return ts_highlights
