local default_plugins = {
 "nvim-lua/plenary.nvim",
 "lewis6991/impatient.nvim",
 "wbthomason/packer.nvim",
 "NvChad/extensions",
 "NvChad/base46",
 "NvChad/nvim-base16.lua",
 "NvChad/nvterm",
 "kyazdani42/nvim-web-devicons",
 "feline-nvim/feline.nvim",
 "akinsho/bufferline.nvim",
 "lukas-reineke/indent-blankline.nvim",
 "NvChad/nvim-colorizer.lua",
 "nvim-treesitter/nvim-treesitter",
 "lewis6991/gitsigns.nvim",
 "neovim/nvim-lspconfig",
 "ray-x/lsp_signature.nvim",
 "andymass/vim-matchup",
 "max397574/better-escape.nvim",
 "rafamadriz/friendly-snippets",
 "hrsh7th/nvim-cmp",
 "L3MON4D3/LuaSnip",
 "saadparwaiz1/cmp_luasnip",
 "hrsh7th/cmp-nvim-lua",
 "hrsh7th/cmp-nvim-lsp",
 "hrsh7th/cmp-buffer",
 "hrsh7th/cmp-path",
 "windwp/nvim-autopairs",
 "goolord/alpha-nvim",
 "numToStr/Comment.nvim",
 "kyazdani42/nvim-tree.lua",
 "nvim-telescope/telescope.nvim",
 "folke/which-key.nvim",
}

return default_plugins
