local primary = function (theme)
  return {
   Normal = { fg = theme.base05, bg = theme.base00, sp_color = nil },
   Bold = { fg = nil, bg = nil, bold = true, },
   Debug = { fg = theme.base08, bg = nil, },
   Directory = { fg = theme.base0D, bg = nil, },
   Error = { fg = theme.base00, bg = theme.base08, },
   ErrorMsg = { fg = theme.base08, bg = theme.base00, },
   Exception = { fg = theme.base08, bg = nil, },
   FoldColumn = { fg = theme.base0C, bg = theme.base01, },
   Folded = { fg = theme.base03, bg = theme.base01, },
   IncSearch = { fg = theme.base01, bg = theme.base09, },
   Italic = { fg = nil, bg = nil, },
   Macro = { fg = theme.base08, bg = nil, },
   MatchParen = { fg = nil, bg = theme.base03, },
   ModeMsg = { fg = theme.base0B, bg = nil, },
   MoreMsg = { fg = theme.base0B, bg = nil, },
   Question = { fg = theme.base0D, bg = nil, },
   Search = { fg = theme.base01, bg = theme.base0A, },
   Substitute = { fg = theme.base01, bg = theme.base0A, },
   sp_colorKey = { fg = theme.base03, bg = nil, },
   TooLong = { fg = theme.base08, bg = nil, },
   Underlined = { fg = theme.base08, bg = nil, },
   Visual = { fg = nil, bg = theme.base02, },
   VisualNOS = { fg = theme.base08, bg = nil, },
   WarningMsg = { fg = theme.base08, bg = nil, },
   WildMenu = { fg = theme.base08, bg = theme.base0A, },
   Title = { fg = theme.base0D, bg = nil, },
   Conceal = { fg = theme.base0D, bg = theme.base00, },
   Cursor = { fg = theme.base00, bg = theme.base05, },
   NonText = { fg = theme.base03, bg = nil, },
   LineNr = { fg = theme.base03, bg = "NONE", },
   SignColumn = { fg = theme.base03, bg = "NONE", },
   StatusLine = { fg = theme.base04, bg = "NONE", },
   StatusLineNC = { fg = theme.base03, bg = "NONE", },
   VertSplit = { fg = theme.base02, bg = "NONE", },
   ColorColumn = { fg = nil, bg = theme.base01, },
   CursorColumn = { fg = nil, bg = theme.base01, },
   CursorLine = { fg = nil, bg = theme.base01, },
   CursorLineNr = { fg = theme.base04, bg = "NONE", },
   QuickFixLine = { fg = nil, bg = theme.base01, },
   PMenu = { fg = theme.base05, bg = theme.base01, },
   PMenuSel = { fg = theme.base01, bg = theme.base05, },
   TabLine = { fg = theme.base03, bg = theme.base01, },
   TabLineFill = { fg = theme.base03, bg = theme.base01, },
   TabLineSel = { fg = theme.base0B, bg = theme.base01, },

    -- Standard syntax highlighting
   Boolean = { fg = theme.base09, bg = nil, },
   Character = { fg = theme.base08, bg = nil, },
   Comment = { fg = theme.base03, bg = nil, },
   Conditional = { fg = theme.base0E, bg = nil, },
   Constant = { fg = theme.base08, bg = nil, },
   Define = { fg = theme.base0E, bg = nil, },
   Delimiter = { fg = theme.base0F, bg = nil, },
   Float = { fg = theme.base09, bg = nil, },
   Function = { fg = theme.base0D, bg = nil, },
   Identifier = { fg = theme.base08, bg = nil, },
   Include = { fg = theme.base0D, bg = nil, },
   Keyword = { fg = theme.base0E, bg = nil, },
   Label = { fg = theme.base0A, bg = nil, },
   Number = { fg = theme.base09, bg = nil, },
   Operator = { fg = theme.base05, bg = nil, },
   PreProc = { fg = theme.base0A, bg = nil, },
   Repeat = { fg = theme.base0A, bg = nil, },
   sp_color = { fg = theme.base0C, bg = nil, },
   sp_colorChar = { fg = theme.base0F, bg = nil, },
   Statement = { fg = theme.base08, bg = nil, },
   StorageClass = { fg = theme.base0A, bg = nil, },
   String = { fg = theme.base0B, bg = nil, },
   Structure = { fg = theme.base0E, bg = nil, },
   Tag = { fg = theme.base0A, bg = nil, },
   Todo = { fg = theme.base0A, bg = theme.base01, },
   Type = { fg = theme.base0A, bg = nil, },
   Typedef = { fg = theme.base0A, bg = nil, },

    -- Diff highlighting DiffAdd = { fg = theme.base0B, bg = theme.base01, },
   DiffChange = { fg = theme.base03, bg = theme.base01, },
   DiffDelete = { fg = theme.base08, bg = theme.base01, },
   DiffText = { fg = theme.base0D, bg = theme.base01, },
   DiffAdded = { fg = theme.base0B, bg = theme.base00, },
   DiffFile = { fg = theme.base08, bg = theme.base00, },
   DiffNewFile = { fg = theme.base0B, bg = theme.base00, },
   DiffLine = { fg = theme.base0D, bg = theme.base00, },
   DiffRemoved = { fg = theme.base08, bg = theme.base00, },

    -- Git highlighting
   gitcommitOverflow = { fg = theme.base08, bg = nil, },
   gitcommitSummary = { fg = theme.base0B, bg = nil, },
   gitcommitComment = { fg = theme.base03, bg = nil, },
   gitcommitUntracked = { fg = theme.base03, bg = nil, },
   gitcommitDiscarded = { fg = theme.base03, bg = nil, },
   gitcommitSelected = { fg = theme.base03, bg = nil, },
   gitcommitHeader = { fg = theme.base0E, bg = nil, },
   gitcommitSelectedType = { fg = theme.base0D, bg = nil, },
   gitcommitUnmergedType = { fg = theme.base0D, bg = nil, },
   gitcommitDiscardedType = { fg = theme.base0D, bg = nil, },
   gitcommitBranch = { fg = theme.base09, bg = nil, bold = true, },
   gitcommitUntrackedFile = { fg = theme.base0A, bg = nil, },
   gitcommitUnmergedFile = { fg = theme.base08, bg = nil, bold = true, },
   gitcommitDiscardedFile = { fg = theme.base08, bg = nil, bold = true, },
   gitcommitSelectedFile = { fg = theme.base0B, bg = nil, bold = true, },

    -- Mail highlighting mailQuoted1 = { fg = theme.base0A, bg = nil, },
   mailQuoted2 = { fg = theme.base0B, bg = nil, },
   mailQuoted3 = { fg = theme.base0E, bg = nil, },
   mailQuoted4 = { fg = theme.base0C, bg = nil, },
   mailQuoted5 = { fg = theme.base0D, bg = nil, },
   mailQuoted6 = { fg = theme.base0A, bg = nil, },
   mailURL = { fg = theme.base0D, bg = nil, },
   mailEmail = { fg = theme.base0D, bg = nil, },

    --, spelling highlighting
   SpellBad = { fg = nil, bg = nil, undercurl = true, sp_color = theme.base08, },
   SpellLocal = { fg = nil, bg = nil, undercurl = true, sp_color = theme.base0C, },
   SpellCap = { fg = nil, bg = nil, undercurl = true, sp_color = theme.base0D, },
   SpellRare = { fg = nil, bg = nil, undercurl = true, sp_color = theme.base0E, },

    -- treesitter
   TSAnnotation = { fg = theme.base0F, bg = nil, },
   TSAttribute = { fg = theme.base0A, bg = nil, },
   TSCharacter = { fg = theme.base08, bg = nil, },
   TSConstBuiltin = { fg = theme.base09, bg = nil, },
   TSConstMacro = { fg = theme.base08, bg = nil, },
   TSError = { fg = theme.base08, bg = nil, },
   TSException = { fg = theme.base08, bg = nil, },
   TSFloat = { fg = theme.base09, bg = nil, },
   TSFuncBuiltin = { fg = theme.base0D, bg = nil, },
   TSFuncMacro = { fg = theme.base08, bg = nil, },
   TSKeywordOperator = { fg = theme.base0E, bg = nil, },
   TSMethod = { fg = theme.base0D, bg = nil, },
   TSNamespace = { fg = theme.base08, bg = nil, },
   TSNone = { fg = theme.base05, bg = nil, },
   TSParameter = { fg = theme.base08, bg = nil, },
   TSParameterReference = { fg = theme.base05, bg = nil, },
   TSPunctDelimiter = { fg = theme.base0F, bg = nil, },
   TSPunctsp_color = { fg = theme.base05, bg = nil, },
   TSStringRegex = { fg = theme.base0C, bg = nil, },
   TSStringEscape = { fg = theme.base0C, bg = nil, },
   TSSymbol = { fg = theme.base0B, bg = nil, },
   TSTagDelimiter = { fg = theme.base0F, bg = nil, },
   TSText = { fg = theme.base05, bg = nil, },
   TSStrong = { fg = nil, bg = nil, bold = true, },
   TSEmphasis = { fg = theme.base09, bg = nil, },
   TSStrike = { fg = theme.base00, bg = nil, strikethrough = true, },
   TSLiteral = { fg = theme.base09, bg = nil, },
   TSURI = { fg = theme.base09, bg = nil, underline = true, },
   TSTypeBuiltin = { fg = theme.base0A, bg = nil, },
   TSVariableBuiltin = { fg = theme.base09, bg = nil, },
   TSDefinition = { fg = nil, bg = nil, underline = true, sp_color = theme.base04, },
   TSDefinitionUsage = { fg = nil, bg = nil, underline = true, sp_color = theme.base04, },
   TSCurrentScope = { fg = nil, bg = nil, bold = true, },
  }
end

return primary
