local symbol_map = {
  Boolean = "",
  Character = "",
  Class = "",
  Color = "",
  Constant = "",
  Constructor = "",
  Enum = "",
  EnumMember = "",
  Event = "ﳅ",
  Field = "",
  File = "",
  Folder = "ﱮ",
  Function = "ﬦ",
  Interface = "",
  Keyword = "",
  Method = "",
  Module = "",
  Number = "",
  Operator = "Ψ",
  Parameter = "",
  Property = "ﰠ",
  Reference = "",
  Snippet = "",
  String = "",
  Struct = "ﯟ",
  Text = "",
  TypeParameter = "",
  Unit = "",
  Value = "",
  Variable = "ﳛ",
  Copilot = ""
}

return symbol_map
